name: Publish Docker Image CI
on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: payned/loveai:tagname
        name: loveai

      - uses: ilteoood/docker_buildx@master
        name: Build & push Docker image
        with:
          publish: true
          dockerFile: Dockerfile
          imageName: loveai/chatgpt
          tag: latest
          platform: linux/arm64
          dockerUser: payned
          dockerPassword: dckr_pat_0eJEwuNJ5GM61NusMLsiqSLzSp0
